SOURCE	= main.cpp
OUT		= build/
CC 		= g++
LFLAGS 	= -static -static-libgcc -static-libstdc++ -O3

all: media volume

media: media.cpp
	$(CC) $(FLAGS) media.cpp -o $(OUT)media.exe $(LFLAGS)

volume: volume.cpp
	$(CC) $(FLAGS) volume.cpp -o $(OUT)volume.exe $(LFLAGS) -lole32

clean:
	del "build" /Q