SOURCE	= main.cpp
OUT		= build/utilFunctions.exe
CC 		= g++
LFLAGS 	= -Ofast -static -static-libgcc -static-libstdc++ -lole32

all: main.cpp
	$(CC) $(FLAGS) main.cpp -o $(OUT) $(LFLAGS) 

clean:
	del "build" /Q